### ISSUE TITLE
Error: Item "The folder name" does not exist in target PO file

### ISSUE THREAD

**Issue by Ahmed-Galal85** [naskio/po-auto-translation#2] opened 2021-03-01 07:49 UTC
Steps were made and in the end, this error was obtained
Error: Item "The folder name" does not exist in target PO file.

**Comment by naskio** [comment] 2021-03-02 05:41
Hello @Ahmed-Galal85,
You can open your PO file and check if it contains the item "The folder name",
The problem is related to your PO file, you are trying to access the translation of a text ("The folder name" in this case) that isn't present in your PO file.
Try to regenerate your PO file or to get a PO template file (POT) that is up-to-date.
I am closing this issue #2  since it is not related to the steps described in this repository.

**Closed as completed by naskio** 2021-03-02 05:41 UTC

**Comment by jvsteiner** [comment] 2022-06-04 14:18
It seems if the source .po file has strings with leading or trailing spaces, these get stripped with the import process into google docs.  Once they are gone, the strings are no longer equivalent, and when you try to convert them back, you get this error.  I confirmed this by manually adding back the correct whitespace into the google doc, redownloading, and confirming the errors go away.  I would say that this is definitely a problem with these steps, although I think there is nothing to can do in your node.js code to prevent it.

Actually maybe there is - you could use a different delimiter.  at least it makes the problem less likely.
